### ISSUE TITLE
Solve a cube by state, not by previous moves?

### ISSUE THREAD

**Issue by vmiklos** [luckasRanarison/kewb#1]
Hi!

Thanks for this crate, looks quite promising. :-) I nicely solves some 24 step scrambles where many other implementations struggle with performance.

If I have a list of moves how a real-world cube state was created, then State::from() already provides this.

However, in case I just have the state of a real world cube, then I have a state, not a list of moves. Is it possible to use your solver to figure out such a state?

Looking at the code, looks like you allow constructing State directly, which looks promising. Looking at SOLVED_STATE, I kind of get the cp and ep fields: e.g. i state that position of UBR now has UFR, I get that. Similar for edges.

But how do I know what to specify for the co and eo fields? Sounds like that's the only missing piece and then solving a state from a real-world cube would be also possible (as a user of your library).

Thanks again.

**Comment by luckasRanarison** [comment]
Hi! Thanks for giving my program a try :), it can search can search 22 moves solutions easily but it's still far from being performant. 
About the EO and CO values, form the moment the solver only provides solutions for the position where you scrambled the cube, so initial position is the EO and CO reference or more precisely the top, down, right and left **centers** are the references. 
Let's take the position where white center is on top and green front as an example, in this position an edge is **correctly** oriented on the top (Up or U) layer if the top sticker is white, yellow, green or blue. Same for the edges on the middle layer (E) and same for the edges on the bottom layer. The EO for a correctly oriented edge is 0, 1 otherwise. 
It's similar for corners but with few differences, a corner is oriented if it has white or yellow sticker on the top or bottom layer, also a corner can have 3 orientations, and a CO value is 1 if the corner is twisted clockwise and 2 of the corner is twisted counter-clockwise.
You can also take a look at this simple 2*2 solver for reference, I hope it helps https://gist.github.com/luckasRanarison/c134ecbcd20661ed2f80dd9396cb2783

**Comment by vmiklos** [comment]
Thanks a lot! Based on your reply + reading http://kociemba.org/math/cubielevel.htm, I guess what I want is possible like this:

```rust
        let state = State {
            //   UBL, UBR, UFR, UFL, DFL, DFR, DBR, DBL
            cp: [UBL, UBR, UFL, DFL, DFR, UFR, DBR, DBL],
            co: [0, 0, 1, 2, 1, 2, 0, 0],
            //   BL, BR, FR, FL, UB, UR, UF, UL, DF, DR, DB, DL
            ep: [BL, BR, UF, DF, UB, UR, FL, UL, FR, DR, DB, DL],
            eo: [0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0],
        };
        let (move_table, pruning_table) = read_table().unwrap();
        let max: u8 = 23;
        let timeout: Option<f32> = None;
        let mut solver = Solver::new(&move_table, &pruning_table, max, timeout);
        let solution = solver.solve(state).unwrap();
        println!("{solution}");
```

Now this is just the state of an F move, but with a bit more work, I guess I should be able to take a real world cube state (which is a result of solved state + moves, but the list of moves is not known). Probably what I need is a conversion from the facelet level to the cubie level, which is not trivial, but should be doable.

I think I'll experiment with such a conversion on my side. Once I have something, you may or may not want to include that in kewb.

**Comment by vmiklos** [comment]
Aha, let me try to do the facelet -> cubie conversion.
